// Creatures Map Editor 1.08 — CAOS world/addon generation recovery.
//
// Prerequisites:
//   all recovery passes through RefineC2EMapEditorRemainingActions.java.
//
// This pass moves outward from the editor model into the generated C2e CAOS.
//
// Exact handler mapping already recovered by MFC:
//   00409FF0 CC2ERoomEditorDoc_OnInjectAsWorld
//   0040A090 CC2ERoomEditorDoc_OnInjectAsAddon
//   0040B730 CC2ERoomEditorDoc_OnExportAsAddon
//   0040B820 CC2ERoomEditorDoc_OnExportAsWorld
//
// All four call 0040A130, with:
//   mode 0 = World
//   mode 1 = Addon
//
// High-confidence generator layers:
//   Doc        0040A130  complete autogenerated world/addon script
//   WorldModel 004242E0  map/metaroom/door/cleanup section
//   MetaRoom   00416D00  addon replacement/preflight section
//   MetaRoom   00416F20  metaroom/background/music/room creation section
//   MetaRoom   004171E0  cleanup of GAME mapeditortmp_<roomId> variables
//   Room       0041A620  already recovered BuildInjectCAOS
//   Room       0041A770  already recovered BuildDeleteCAOS
//
// @category C2E Map Editor
// @author OpenAI

import java.util.*;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.data.*;
import ghidra.program.model.lang.Register;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.SourceType;

public class RefineC2EMapEditorCAOSWorkflows extends GhidraScript {

    private static final CategoryPath CAT = new CategoryPath("/C2E/Refined");

    private DataTypeManager dtm;
    private Structure docType;
    private Structure worldType;
    private Structure metaRoomType;

    private Pointer docPtr;
    private Pointer worldPtr;
    private Pointer metaRoomPtr;

    private int functionsCreated;
    private int functionsRenamed;
    private int functionsKept;
    private int thisTypesApplied;
    private int thisTypesSkipped;
    private int returnTypesApplied;
    private int labelsCreated;

    private static class FuncSpec {
        final long address;
        final String name;
        final String owner;
        final String comment;
        final String returnKind;

        FuncSpec(long address, String name, String owner,
                 String comment, String returnKind) {
            this.address = address;
            this.name = name;
            this.owner = owner;
            this.comment = comment;
            this.returnKind = returnKind;
        }
    }

    private static class LabelSpec {
        final long address;
        final String name;
        final String comment;

        LabelSpec(long address, String name, String comment) {
            this.address = address;
            this.name = name;
            this.comment = comment;
        }
    }

    private final FuncSpec[] FUNCTIONS = new FuncSpec[] {
        new FuncSpec(
            0x40a130L,
            "CC2ERoomEditorDoc_WriteWorldOrAddonCAOS",
            "doc",
            "Shared CAOS-script writer used by InjectAsWorld, InjectAsAddon, ExportAsWorld and ExportAsAddon. The mode argument is false for World and true for Addon. Writes the autogenerated header/counts, invokes C2EWorldModel_WriteWorldOrAddonCAOS, and for World mode also emits all 16x20 RATE commands.",
            "void"),

        new FuncSpec(
            0x422ae0L,
            "C2EWorldModel_GetRoomCount",
            "world",
            "Counts compact Rooms across all metarooms. Used in the autogenerated '* N metarooms, N rooms, N doors' header and elsewhere in the UI.",
            "int"),

        new FuncSpec(
            0x4242e0L,
            "C2EWorldModel_WriteWorldOrAddonCAOS",
            "world",
            "Writes the world-model portion of an autogenerated CAOS script. World mode emits MAPD map dimensions; Addon mode emits per-metaroom replacement/preflight code before creation. Both modes create metarooms/rooms, emit DOOR commands from doorSegments, and append cleanup code for temporary GAME variables.",
            "void"),

        new FuncSpec(
            0x416d00L,
            "C2EEditorMetaRoom_WriteAddonReplacementCAOS",
            "metaroom",
            "Addon-only metaroom preflight/replacement generator. Locates an existing metaroom at the same centre with GMAP, requires the same background, refuses replacement while non-carried agents remain, deletes all rooms in the old metaroom and then DELM deletes the metaroom.",
            "void"),

        new FuncSpec(
            0x416f20L,
            "C2EEditorMetaRoom_WriteCreateCAOS",
            "metaroom",
            "Writes CAOS to create one compact editor metaroom: ADDM using bounds/background, MMSC metaroom music, ADDB for additional backgrounds, then each Room's ADDR/RTYP/RMSC/game-mapeditortmp creation code.",
            "void"),

        new FuncSpec(
            0x4171e0L,
            "C2EEditorMetaRoom_WriteCleanupCAOS",
            "metaroom",
            "Writes cleanup CAOS for every room in this metaroom by calling C2EEditorRoom_BuildDeleteCAOS. These DELG commands delete GAME mapeditortmp_<roomId> variables after generated DOOR commands have consumed them.",
            "void")
    };

    private final LabelSpec[] LABELS = new LabelSpec[] {
        new LabelSpec(0x434624L, "C2E_CAOS_AUTOGENERATED_HEADER",
            "* Autogenerated by the Creatures Map Editor"),
        new LabelSpec(0x4345f4L, "C2E_CAOS_INFO_COMMENT",
            "* For more info see http://cdn.creatures.net"),
        new LabelSpec(0x434568L, "C2E_CAOS_WORLD_MODE_COMMENT",
            "* World file: existing map deleted, CA rates written"),
        new LabelSpec(0x4345a0L, "C2E_CAOS_ADDON_MODE_COMMENT",
            "* Addon file: deletes existing metarooms at the same place, same background name"),
        new LabelSpec(0x434544L, "C2E_CAOS_COUNTS_COMMENT_FORMAT",
            "* %d metarooms, %d rooms, %d doors"),
        new LabelSpec(0x434374L, "C2E_CAOS_RATE_FORMAT",
            "rate %d %d %f %f %f"),
        new LabelSpec(0x434d64L, "C2E_CAOS_ADDON_METAROOM_PREFLIGHT_FORMAT",
            "GMAP/BKDS addon same-location/same-background check."),
        new LabelSpec(0x434960L, "C2E_CAOS_ADDON_AGENT_GUARD_SNIPPET",
            "Addon replacement guard: refuses to replace a metaroom while an agent remains in it."),
        new LabelSpec(0x434b98L, "C2E_CAOS_DELETE_EXISTING_METAROOM_SNIPPET",
            "Deletes all rooms listed by ERID, then DELM deletes the old metaroom."),
        new LabelSpec(0x434e80L, "C2E_CAOS_ADDM_FORMAT",
            "setv game \"mapeditortmp\" addm ..."),
        new LabelSpec(0x434e70L, "C2E_CAOS_MMSC_FORMAT",
            "mmsc %d %d \"%s\""),
        new LabelSpec(0x434e50L, "C2E_CAOS_ADDB_FORMAT",
            "addb game \"mapeditortmp\" \"%s\""),
        new LabelSpec(0x434e3cL, "C2E_CAOS_METAROOM_TEMP_GAMEVAR",
            "game \"mapeditortmp\""),
        new LabelSpec(0x4353b0L, "C2E_CAOS_MAPD_FORMAT",
            "mapd %d %d"),
        new LabelSpec(0x435354L, "C2E_CAOS_DOOR_FORMAT",
            "door game \"mapeditortmp_%d\" game \"mapeditortmp_%d\" %d"),
        new LabelSpec(0x435344L, "C2E_CAOS_CLEANUP_STATUS",
            "Clean Up Code"),
        new LabelSpec(0x43538cL, "C2E_CAOS_WRITING_DOORS_STATUS",
            "Writing Doors"),
        new LabelSpec(0x43539cL, "C2E_CAOS_WRITING_METAROOM_STATUS_FORMAT",
            "Writing Metaroom %d"),
        new LabelSpec(0x434650L, "C2E_CAOS_DBG_PAUSE",
            "dbg: paws"),
        new LabelSpec(0x43465cL, "C2E_CAOS_DBG_PLAY",
            "dbg: play")
    };

    @Override
    public void run() throws Exception {
        if (currentProgram == null) {
            popup("Open the latest recovered MapEditor.exe database first.");
            return;
        }

        if (currentProgram.getDefaultPointerSize() != 4) {
            popup("This pass is deliberately limited to the 32-bit Map Editor target.");
            return;
        }

        // Exact target guards: immediate operands of three format-string pushes.
        if (getInt(toAddr(0x40a196L)) != 0x00434624 ||
            getInt(toAddr(0x416fa8L)) != 0x00434e80 ||
            getInt(toAddr(0x424330L)) != 0x004353b0) {

            popup("MapEditor 1.08 CAOS-workflow identity guard failed.");
            return;
        }

        dtm = currentProgram.getDataTypeManager();

        docType = requireStructure("CC2ERoomEditorDoc_refined");
        worldType = requireStructure("C2EWorldModel");
        metaRoomType = requireStructure("C2EEditorMetaRoom");

        docPtr = new PointerDataType(docType, dtm);
        worldPtr = new PointerDataType(worldType, dtm);
        metaRoomPtr = new PointerDataType(metaRoomType, dtm);

        println("=== Creatures Map Editor 1.08 - CAOS workflow recovery ===");
        println("");

        for (LabelSpec spec : LABELS) {
            labelConstant(spec);
        }

        for (FuncSpec spec : FUNCTIONS) {
            monitor.checkCancelled();

            Function f = ensureFunction(spec.address, spec.name);
            if (f == null) continue;

            appendRepeatableComment(
                f.getEntryPoint(),
                "[C2E CAOS workflows] " + spec.comment);

            if ("doc".equals(spec.owner)) {
                applyThisType(f, docPtr, "CC2ERoomEditorDoc_refined");
            }
            else if ("world".equals(spec.owner)) {
                applyThisType(f, worldPtr, "C2EWorldModel");
            }
            else if ("metaroom".equals(spec.owner)) {
                applyThisType(f, metaRoomPtr, "C2EEditorMetaRoom");
            }

            applyReturnType(f, spec.returnKind);
        }

        annotateHandlers();
        annotateWorldGrammar();
        annotateAddonSemantics();
        annotateCleanupSemantics();

        println("");
        println("Running analysis on CAOS workflow changes...");
        analyzeChanges(currentProgram);

        println("");
        println("=== CAOS workflow summary ===");
        println("Functions created:    " + functionsCreated);
        println("Functions renamed:    " + functionsRenamed);
        println("Existing names kept:  " + functionsKept);
        println("this types applied:   " + thisTypesApplied);
        println("this types skipped:   " + thisTypesSkipped);
        println("return types applied: " + returnTypesApplied);
        println("labels created:       " + labelsCreated);
        println("");
        println("Recovered workflow:");
        println("  Inject/Export World/Addon");
        println("        -> Doc_WriteWorldOrAddonCAOS");
        println("        -> WorldModel_WriteWorldOrAddonCAOS");
        println("        -> MetaRoom addon preflight/create/cleanup");
        println("        -> Room ADDR/RTYP/RMSC temporary GAME vars");
        println("        -> DOOR commands");
        println("        -> cleanup DELG");
    }

    private void labelConstant(LabelSpec spec) {
        try {
            Address a = toAddr(spec.address);

            if (getSymbolAt(a) == null ||
                getSymbolAt(a).getSource() == SourceType.DEFAULT) {
                createLabel(a, spec.name, true);
                labelsCreated++;
                println("[label] " + a + " -> " + spec.name);
            }

            String old = getEOLComment(a);
            if (old == null || old.isBlank()) {
                setEOLComment(a, spec.comment);
            }
            else if (!old.contains(spec.comment)) {
                setEOLComment(a, old + "\n" + spec.comment);
            }
        }
        catch (Exception e) {
            println("[label-skip] " + Long.toHexString(spec.address) +
                " " + spec.name + ": " + e.getMessage());
        }
    }

    private void annotateHandlers() {
        appendRepeatableComment(
            toAddr(0x409ff0L),
            "[C2E CAOS workflow] Inject As World -> CC2ERoomEditorDoc_WriteWorldOrAddonCAOS(..., isAddon=false). Uses the live-game output path.");

        appendRepeatableComment(
            toAddr(0x40a090L),
            "[C2E CAOS workflow] Inject As Addon -> CC2ERoomEditorDoc_WriteWorldOrAddonCAOS(..., isAddon=true). Uses the live-game output path.");

        appendRepeatableComment(
            toAddr(0x40b730L),
            "[C2E CAOS workflow] Export As Addon writes !addon.cos then calls CC2ERoomEditorDoc_WriteWorldOrAddonCAOS(..., isAddon=true).");

        appendRepeatableComment(
            toAddr(0x40b820L),
            "[C2E CAOS workflow] Export As World writes !world.cos then calls CC2ERoomEditorDoc_WriteWorldOrAddonCAOS(..., isAddon=false).");
    }

    private void annotateWorldGrammar() {
        appendRepeatableComment(
            toAddr(0x4242e0L),
            "[C2E generated CAOS order]\n" +
            "World mode:\n" +
            "  MAPD mapWidth mapHeight\n" +
            "  each metaroom: create metaroom/background/music/rooms\n" +
            "  each generated door: DOOR game mapeditortmp_room1 game mapeditortmp_room2 permeability\n" +
            "  cleanup: DELG each room temporary GAME variable\n" +
            "Addon mode:\n" +
            "  each metaroom: same-location/background replacement preflight\n" +
            "  then the same create / door / cleanup sequence.\n" +
            "World-only RATE commands are emitted by the enclosing document writer after this function.");

        appendRepeatableComment(
            toAddr(0x40a130L),
            "[C2E generated script envelope]\n" +
            "Writes autogenerated/info comments and metaroom/room/door counts. " +
            "World mode additionally handles map replacement/live-game checks and emits all 16 room types x 20 CA RATE triples. " +
            "Addon mode omits global RATE replacement and uses per-metaroom safe replacement semantics.");
    }

    private void annotateAddonSemantics() {
        appendRepeatableComment(
            toAddr(0x416d00L),
            "[C2E addon semantics]\n" +
            "Generated CAOS uses GMAP at the editor metaroom centre. If a metaroom exists there, BKDS must match the expected background. " +
            "A generated ENUM scan refuses replacement when a non-carried agent remains. " +
            "If safe, ERID supplies existing room IDs, DELR removes them, and DELM removes the old metaroom before recreation.");

        setEOLComment(
            toAddr(0x416e3aL),
            "Format complete GMAP/BKDS/addon replacement preflight block.");

        setEOLComment(
            toAddr(0x416e91L),
            "User-visible failure: existing metaroom cannot be deleted while an agent remains.");

        setEOLComment(
            toAddr(0x416ec5L),
            "User-visible failure: same-position metaroom has a different background.");
    }

    private void annotateCleanupSemantics() {
        appendRepeatableComment(
            toAddr(0x4171e0L),
            "[C2E cleanup semantics] This does not delete C2e rooms. It emits DELG for GAME \"mapeditortmp_<roomId>\" variables created by C2EEditorRoom_BuildInjectCAOS. Those GAME vars exist only so later generated DOOR commands can refer to the newly created rooms.");

        appendRepeatableComment(
            toAddr(0x41a620L),
            "[C2E generated-room role] ADDR creates the room and stores the resulting room handle/address in GAME \"mapeditortmp_<roomId>\". RTYP and RMSC are emitted before WorldModel writes DOOR commands.");

        appendRepeatableComment(
            toAddr(0x41a770L),
            "[C2E generated-room role] DELG here removes only the temporary GAME variable \"mapeditortmp_<roomId>\" after door generation; it is cleanup, not DELR room deletion.");
    }

    private Structure requireStructure(String name) {
        DataType dt = dtm.getDataType(CAT, name);

        if (!(dt instanceof Structure)) {
            throw new IllegalStateException(
                "Missing /C2E/Refined/" + name +
                ". Run the previous recovery passes first.");
        }

        return (Structure)dt;
    }

    private Function ensureFunction(long value, String desiredName) throws Exception {
        Address a = toAddr(value);
        Function f = getFunctionAt(a);

        if (f == null) {
            Function containing = getFunctionContaining(a);

            if (containing != null &&
                !containing.getEntryPoint().equals(a)) {

                println("[function-overlap-skip] " + a +
                    " lies inside " + containing.getName());
                return null;
            }

            if (getInstructionAt(a) == null && !disassemble(a)) {
                println("[disassemble-fail] " + a + " " + desiredName);
                return null;
            }

            f = createFunction(a, desiredName);

            if (f == null) {
                println("[function-create-fail] " + a + " " + desiredName);
                return null;
            }

            functionsCreated++;
            println("[create] " + a + " -> " + desiredName);
        }

        String current = f.getName();

        if (current.equals(desiredName)) {
            functionsKept++;
        }
        else if (current.startsWith("FUN_") ||
                 current.startsWith("thunk_FUN_") ||
                 f.getSymbol().getSource() == SourceType.DEFAULT) {

            f.setName(desiredName, SourceType.USER_DEFINED);
            functionsRenamed++;
            println("[rename] " + a + " -> " + desiredName);
        }
        else {
            functionsKept++;
            println("[keep] " + a + " existing=" + current +
                " suggested=" + desiredName);
        }

        return f;
    }

    private void applyThisType(Function f, Pointer ptr, String typeName) {
        try {
            if (f.hasVarArgs()) {
                thisTypesSkipped++;
                return;
            }

            Register ecx = currentProgram.getRegister("ECX");
            if (ecx == null) {
                thisTypesSkipped++;
                return;
            }

            Parameter[] oldParams = f.getParameters();

            if (f.hasCustomVariableStorage() &&
                oldParams.length > 0 &&
                "this".equals(oldParams[0].getName()) &&
                oldParams[0].getDataType() != null &&
                oldParams[0].getDataType().isEquivalent(ptr) &&
                oldParams[0].getVariableStorage() != null &&
                oldParams[0].getVariableStorage().isRegisterStorage()) {

                return;
            }

            ArrayList<Variable> newParams = new ArrayList<>();

            newParams.add(
                new ParameterImpl(
                    "this",
                    ptr,
                    ecx,
                    currentProgram,
                    SourceType.USER_DEFINED));

            for (Parameter p : oldParams) {
                if (p.isAutoParameter() ||
                    "this".equals(p.getName())) {
                    continue;
                }

                VariableStorage storage = p.getVariableStorage();

                if (storage != null &&
                    storage.isRegisterStorage() &&
                    storage.getRegister() != null &&
                    storage.getRegister().equals(ecx)) {

                    println("[drop-ecx-param] " + f.getEntryPoint() +
                        " dropping old " + p.getName() + "{" + storage + "}");
                    continue;
                }

                newParams.add(new ParameterImpl(p, currentProgram));
            }

            f.updateFunction(
                "__thiscall",
                null,
                newParams,
                Function.FunctionUpdateType.CUSTOM_STORAGE,
                true,
                SourceType.USER_DEFINED);

            thisTypesApplied++;

            println("[this] " + f.getEntryPoint() + " " +
                f.getName() + " -> " + typeName + " * @ ECX");
        }
        catch (Exception e) {
            thisTypesSkipped++;
            println("[this-fail] " + f.getEntryPoint() +
                " " + f.getName() + ": " + e.getMessage());
        }
    }

    private void applyReturnType(Function f, String kind) {
        try {
            DataType type = null;

            if ("void".equals(kind)) {
                type = VoidDataType.dataType;
            }
            else if ("int".equals(kind)) {
                type = IntegerDataType.dataType;
            }

            if (type != null &&
                (f.getReturnType() == null ||
                 !f.getReturnType().isEquivalent(type))) {

                f.setReturnType(type, SourceType.USER_DEFINED);
                returnTypesApplied++;
            }
        }
        catch (Exception e) {
            println("[return-skip] " + f.getEntryPoint() +
                " " + f.getName() + ": " + e.getMessage());
        }
    }

    private void appendRepeatableComment(Address a, String text) {
        String old = getRepeatableComment(a);

        if (old == null || old.isBlank()) {
            setRepeatableComment(a, text);
        }
        else if (!old.contains(text)) {
            setRepeatableComment(a, old + "\n" + text);
        }
    }
}
